INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (1,'3','Canberra','Sydney','Melbourne','Canberra','Perth','1','What is the capital city of Australia?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (2,'1','15 August 1947','15 August 1947','26 January 1961','14 August 1947','30 November 1996','1','When did India gain independence?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (3,'1','Isaac Newton','Isaac Newton','Leonardo Da Vinci','Nikola Tesla','Thomas Edison','1','Who discovered gravity?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (4,'2','Galileo Galilei','Leonardo Da Vinci','Galileo Galilei','Wright Brothers','Archimedes','1','Who is known for the invention of the telescope?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (5,'2','Nevada','Utah','Nevada','Nebraska','Montana','1','Where is Area 51 present?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (6,'2','Leonardo da Vinci','Vincent van Gogh','Leonardo da Vinci','Pablo Picasso','Michelangelo','1','Who painted the Mona Lisa?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (7,'4','Sahara Desert','Thar Desert','Namib Desert','Gobi Desert','Sahara Desert','1','Which is the largest desert in the world?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (8,'3','China','Russia','USA','China','India','1','Which country has the largest army in the world?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (9,'4','Mount Everest','K2','Mount Kilimanjaro','Denali','Mount Everest','1','What is the tallest mountain in the world?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (10,'1','Malala Yousafzai','Malala Yousafzai','Nishita Sinha','Gabriel Boric','Bhumibol Adulyadej','1','Who became the youngest person to win a Nobel Peace Prize at age 17 in 2014?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (11,'1','Jupiter','Jupiter','Saturn','Earth','Mars','1','What is the largest planet in our solar system?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (12,'2','Netherlands','France','Netherlands','Italy','Spain','1','Which country is famous for its tulip fields and windmills?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (13,'1','Yen','Yen','Euro','Dollar','Pound','1','What is the currency of Japan?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (14,'1','William Shakespeare','William Shakespeare','Oscar Wilde','Jane Austen','Charles Dickens','1','Who wrote the play "Romeo and Juliet"?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (15,'1','Mount Everest',' Mount Everest','Mount Kilimanjaro','Mount McKinley','Mount Fuji','1','What is the tallest mountain in the world?');

INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (16,'2','12','11','12','13','14','2','What is the square root of 144?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (17,'2','6','3','6','8','4','2','What is the highest common factor of the numbers 30 and 132?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (18,'3','9','12','15','9','3','2','Which number is the equivalent to 3^(4)/3^(2)? ');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (19,'1','400','400','412','390','410','2','What is next in the following number series: 256, 289, 324, 361 . . . ?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (20,'1','4.0','4.0','-4.0','5.0','3.5','2','What is the floor of 4.5?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (21,'4','011','101','111','100','011','2','What is the binary representation of 3?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (22,'1','2','2','4','7','3','2','What is the smallest prime number?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (23,'1','22/7','22/7','55/3','8/3','31/7','2','What is the value of pi?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (24,'2','-1','1','-1','1/2','0','2','What is the product of slopes of two perpendicular lines?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (25,'2','32 units','24 units','32 units','40 units','64 units','2','If a square has a side length of 8 units, what is its perimeter?');

INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (26,'2','Barry Bonds','Babe Ruth','Barry Bonds','Hank Aaron','Alex Rodriguez','3','Who holds the record for the most home runs in Major League Baseball history?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (27,'3','Cristiano Ronaldo','Neymar','Lionel Messi','Cristiano Ronaldo','Luis Suarez','3','Which footballer has won the Ballond\'or Award 5 times?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (28,'1','France','France','Brazil','Germany','Argentina','3','Which country won the FIFA World Cup in 2018?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (29,'1','91','91','101','54','78','3','What is the record of most goals scored in a year?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (30,'2','Michael Schumacer','Lewis Hamilton','Michael Schumacer','Ayrton Senna','Nikki Lauda','3','Who has the most Formula 1 championships?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (31,'2','Michael Phelps','Usain Bolt','Michael Phelps','Simone Biles','Serena Williams','3','Which athlete has won the most Olympic gold medals of all time?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (32,'2','Magnus Carlsen','Bobby Fisher','Magnus Carlsen','Hikaru Nakamura','Anish Giri','3','Who is the current chess champion?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (33,'3','Paris Saint Germain','Real Madrid C.F.','F.C. Barcelona','Paris Saint Germain','Boca Juniors','3','What club does Lionel Messi play for?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (34,'2','Stephen Curry','Michael Jordan','Stephen Curry','LeBron James','Wilt Chamberlain','3','Who was the only unanimous NBA MVP?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (35,'4','Ben Roethlisberger','Patrick Mahomes','Aaron Rodgers','Tom Brady','Ben Roethlisberger','3','Who is the youngest quarterback to win a super-bowl?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (36,'2','Golden State Warriors','Cleveland Caviliers','Golden State Warriors','Chicago Bulls','Boston Celtics','3','Which team has the best NBA regular season record?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (37,'2','New England Patriots','Dallas Cowboys','New England Patriots','Pittsburgh Steelers','Green Bay Packers','3','Which team has won the most Super Bowl titles in NFL history?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (38,'1','Michael Jordan','Michael Jordan','LeBron James','Kobe Bryant','Magic Johnson','3','Who is considered the greatest basketball player of all time?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (39,'1','Roger Federer','Roger Federer','Rafael Nadal','Novak Djokovic','Serena Williams','3','In tennis, which player has the most Grand Slam singles titles in history?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (40,'1','United States','United States','Soviet Union','China','Germany','3','Which country has won the most Olympic gold medals in the history of the Summer Olympics?');

INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (41,'1','O','O','Oc','Om','Ox','4','What is the chemical symbol for the element oxygen?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (42,'4','Skin','Heart','Brain','Liver','Skin','4','What is the largest organ in the human body?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (43,'2','Mars','Venus','Mars','Jupiter','Saturn','4','Which planet is known as the Red Planet?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (44,'1','Photosynthesis','Photosynthesis','Respiration','Transpiration','Germination','4','What is the process by which plants convert sunlight into energy called?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (45,'1','Atom','Atom','Cell','Molecule','Electron','4','Which of the following is the smallest unit of matter?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (46,'2','100 degrees Celsius','0 degrees Celsius','100 degrees Celsius','212 degrees Celsius','373 degrees Celsius','4','What is the boiling point of water in Celsius?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (47,'3','Ampere','Volt','Watt','Ampere','Ohm','4','What is the unit of measurement for electric current?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (48,'3','Nuclear power','Solar power','Wind power','Nuclear power','Hydropower','4','Which of the following is not a type of renewable energy?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (49,'1','Biology','Biology','Chemistry','Physics','Geology','4','What is the study of living organisms called?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (50,'2','Albert Einstein','Isaac Newton','Albert Einstein','Galileo Galilei','Nikola Tesla','4','Which scientist proposed the theory of relativity?');

INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (51,'2','George Washington','Thomas Jefferson','George Washington','Abraham Lincoln','John F. Kennedy','5','Who was the first President of the United States?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (52,'3','1945','1941','1943','1945','1947','5','In which year did World War II end?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (53,'4','Chinese','Roman Empire','Ancient Egyptians','Aztecs','Chinese','5','Which civilization built the Great Wall of China?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (54,'4','King John','Charlemagne','Julius Caesar','King Arthur','King John','5','The Magna Carta, signed in 1215, is an important historical document that limited the power of which ruler?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (55,'2','Joseph Stalin','Vladimir Lenin','Joseph Stalin','Nikita Khrushchev','Mikhail Gorbachev','5','Who was the leader of the Soviet Union during World War II?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (56,'2','1789','1776','1789','1804','1848','5','The French Revolution began in which year?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (57,'1','Christopher Columbus','Christopher Columbus','Ferdinand Magellan','Vasco da Gama','Marco Polo','5','Which famous explorer is credited with discovering America?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (58,'1','Italy','Italy','England','France','Spain','5','The Renaissance period originated in which country?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (59,'1','Martin Luther King Jr.','Martin Luther King Jr.','Malcolm X','Rosa Parks','Abraham Lincoln','5','Who was the leader of the civil rights movement in the United States during the 1960s?');
INSERT INTO brain_battle.questions (`Id`,`answerOption`,`answer`,`option1`,`option2`,`option3`,`option4`,`categoryId`,`description`) VALUES (60,'3','England','United States','Germany','England','Japan','5','The Industrial Revolution began in which country?');


